export let task_types = {
    SHOW_MODAL: 'SHOW_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    ADD_TASK: 'ADD_TASK',
    GET_TASK: 'GET_TASK',
    SET_TASK_COUNTER: 'SET_TASK_COUNTER',
    TOGGLE_FETCHING: 'TOGGLE_FETCHING'
}