const TaskTypes = {
  ADD_TASK: "ADD_TASK",
  CHANGE_TASK: "CHANGE_TASK",
  CHANGE_DESCRIPTION: "CHANGE_DESCRIPTION",
  CHANGE_ADDRESS: "CHANGE_ADDRESS",
  CHANGE_COST: "CHANGE_COST",
  GET_USER_LOCATION: "GET_USER_LOCATION"
};

export default TaskTypes;
